# Generated by Django 4.0.3 on 2022-04-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_question_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exam_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='last_seen',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
