# Generated by Django 3.2.8 on 2022-05-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0004_choose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.CharField(blank=True, max_length=5, null=True)),
                ('registration_start_date', models.DateField()),
                ('registration_last_date', models.DateField()),
                ('exam_start_date', models.DateField()),
                ('exam_start_time', models.TimeField()),
                ('exam_end_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='result',
            name='exam_status',
            field=models.BooleanField(default=True),
        ),
    ]
