# Generated by Django 3.2.8 on 2022-05-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0005_auto_20220503_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_feedback',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
