# Generated by Django 3.2.8 on 2022-05-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0008_auto_20220504_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_field',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='question',
            name='ques_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='board_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
