# Generated by Django 3.2.8 on 2022-05-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0009_auto_20220515_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image_field',
        ),
        migrations.AddField(
            model_name='question',
            name='image_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
